version: 2.0

jobs:
  # -----------------------------------------------------------------------------------------------
  # ----- BUILD -----------------------------------------------------------------------------------
  # -----------------------------------------------------------------------------------------------
  build:
    working_directory: /go/src/github.com/geoffmore/esctl
    docker:
      - image: circleci/golang:1.11
        environment:
          # https://github.com/cloudfoundry/go-buildpack/issues/71
          GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: Get the Package
          command: go get -v -t -d ./...
      - run:
          name: Build the Package
          command: |
            go mod verify
            go build -v github.com/geoffmore/esctl/cmd/esctl...
